name: paaieds
description: "Plataforma de Aprendizaje Asistida por IA para la Especialización
  en Desarrollo de Software "
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  animate_do: ^4.2.0
  cached_network_image: ^3.4.1
  cloud_firestore: ^6.0.3
  cupertino_icons: ^1.0.8
  firebase_auth: ^6.1.1
  firebase_core: ^4.2.0
  firebase_storage: ^13.0.3
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_spinkit: ^5.2.2
  flutter_svg: ^2.2.1
  font_awesome_flutter: ^10.7.0
  google_fonts: ^6.2.1
  http: ^1.5.0
  image_picker: ^1.2.0
  motion_snackbar: ^0.0.6

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - .env
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/paaieds.png"
  min_sdk_android: 21
