// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMGroaXKYQT9IYdIqFGs7B39StXBaVc7Y',
    appId: '1:970074206707:web:c6d96d30857842729ea286',
    messagingSenderId: '970074206707',
    projectId: 'api-paaieds',
    authDomain: 'api-paaieds.firebaseapp.com',
    storageBucket: 'api-paaieds.firebasestorage.app',
    measurementId: 'G-BF9JP1ZKVE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqea0qGy49Ie2yhqG2Leq8Htv_P9l8F00',
    appId: '1:970074206707:android:fb97ccd411f308109ea286',
    messagingSenderId: '970074206707',
    projectId: 'api-paaieds',
    storageBucket: 'api-paaieds.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtYKPJea_0WitVD-JFpQvOYRZfNsGvBwA',
    appId: '1:970074206707:ios:ed668121eec35ca99ea286',
    messagingSenderId: '970074206707',
    projectId: 'api-paaieds',
    storageBucket: 'api-paaieds.firebasestorage.app',
    iosBundleId: 'com.example.paaieds',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtYKPJea_0WitVD-JFpQvOYRZfNsGvBwA',
    appId: '1:970074206707:ios:ed668121eec35ca99ea286',
    messagingSenderId: '970074206707',
    projectId: 'api-paaieds',
    storageBucket: 'api-paaieds.firebasestorage.app',
    iosBundleId: 'com.example.paaieds',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMGroaXKYQT9IYdIqFGs7B39StXBaVc7Y',
    appId: '1:970074206707:web:2f4a5ce1d2b157ed9ea286',
    messagingSenderId: '970074206707',
    projectId: 'api-paaieds',
    authDomain: 'api-paaieds.firebaseapp.com',
    storageBucket: 'api-paaieds.firebasestorage.app',
    measurementId: 'G-NPTMJF590X',
  );
}
